version: "3.7"
services:
  db:
    image: docker.arvancloud.ir/postgres:17
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data

  redis:
    image: docker.arvancloud.ir/redis:7
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env
    command:
      # Save if 100 keys are added in every 10 seconds
      - "--save 10 100"
      # Set password
      - "--requirepass ${REDIS_PASSWORD}"
  
  networks:

  backend_network:
    driver: bridge
      
  volumes:
  postgres_data:
    driver: local
  