"""equipment_model

Revision ID: 0065a55c09bc
Revises: e5712ae60be7
Create Date: 2024-06-08 11:12:29.891023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0065a55c09bc'
down_revision = 'e5712ae60be7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=30), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.Column('additional_data', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parking_id'], ['parking.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_created'), 'equipment', ['created'], unique=False)
    op.create_index(op.f('ix_equipment_id'), 'equipment', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_is_deleted'), 'equipment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_equipment_modified'), 'equipment', ['modified'], unique=False)
    op.alter_column('parking', 'location_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=True)
    op.alter_column('parking', 'location_lon',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking', 'location_lon',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('parking', 'location_lat',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_index(op.f('ix_equipment_modified'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_is_deleted'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_created'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
