"""pricing_fee_fields

Revision ID: 058a6339167c
Revises: bf2bae3498fe
Create Date: 2024-06-09 14:02:57.543759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058a6339167c'
down_revision = 'bf2bae3498fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('entrance_fee', sa.BigInteger(), nullable=True))
    op.add_column('price', sa.Column('hourly_fee', sa.BigInteger(), nullable=True))
    op.add_column('price', sa.Column('daily_fee', sa.BigInteger(), nullable=True))
    op.add_column('price', sa.Column('penalty_fee', sa.BigInteger(), nullable=True))
    op.add_column('price', sa.Column('expiration_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'expiration_datetime')
    op.drop_column('price', 'penalty_fee')
    op.drop_column('price', 'daily_fee')
    op.drop_column('price', 'hourly_fee')
    op.drop_column('price', 'entrance_fee')
    # ### end Alembic commands ###
