"""model_image

Revision ID: 062b54e831e6
Revises: 3794f0a04522
Create Date: 2024-04-16 11:39:54.408466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062b54e831e6'
down_revision = '3794f0a04522'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_created'), 'image', ['created'], unique=False)
    op.create_index(op.f('ix_image_is_deleted'), 'image', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_image_modified'), 'image', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_modified'), table_name='image')
    op.drop_index(op.f('ix_image_is_deleted'), table_name='image')
    op.drop_index(op.f('ix_image_created'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
