"""add events into notifications

Revision ID: 087eecd32228
Revises: 2e105cb60f58
Create Date: 2024-11-20 10:17:05.752409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087eecd32228'
down_revision = '2e105cb60f58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'event', ['event_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'event_id')
    # ### end Alembic commands ###
