"""model_parking

Revision ID: 0a1f1094aaf7
Revises: 73daf68b84ba
Create Date: 2024-04-16 11:48:17.435841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1f1094aaf7'
down_revision = '73daf68b84ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('floor_name', sa.String(), nullable=True),
    sa.Column('name_parking', sa.String(), nullable=True),
    sa.Column('percent_rotation_rectangle_small', sa.Integer(), nullable=True),
    sa.Column('percent_rotation_rectangle_big', sa.Integer(), nullable=True),
    sa.Column('coordinates_rectangle_big', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('coordinates_rectangle_small', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('number_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ocr', sa.String(), nullable=True),
    sa.Column('latest_time_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('ocr_img_id', sa.Integer(), nullable=True),
    sa.Column('lpr_img_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['lpr_img_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_img_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_camera_id'), 'parking', ['camera_id'], unique=False)
    op.create_index(op.f('ix_parking_coordinates_rectangle_big'), 'parking', ['coordinates_rectangle_big'], unique=False)
    op.create_index(op.f('ix_parking_coordinates_rectangle_small'), 'parking', ['coordinates_rectangle_small'], unique=False)
    op.create_index(op.f('ix_parking_created'), 'parking', ['created'], unique=False)
    op.create_index(op.f('ix_parking_id'), 'parking', ['id'], unique=False)
    op.create_index(op.f('ix_parking_is_deleted'), 'parking', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_parking_latest_time_modified'), 'parking', ['latest_time_modified'], unique=False)
    op.create_index(op.f('ix_parking_lpr_img_id'), 'parking', ['lpr_img_id'], unique=False)
    op.create_index(op.f('ix_parking_modified'), 'parking', ['modified'], unique=False)
    op.create_index(op.f('ix_parking_ocr_img_id'), 'parking', ['ocr_img_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_ocr_img_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_modified'), table_name='parking')
    op.drop_index(op.f('ix_parking_lpr_img_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_latest_time_modified'), table_name='parking')
    op.drop_index(op.f('ix_parking_is_deleted'), table_name='parking')
    op.drop_index(op.f('ix_parking_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_created'), table_name='parking')
    op.drop_index(op.f('ix_parking_coordinates_rectangle_small'), table_name='parking')
    op.drop_index(op.f('ix_parking_coordinates_rectangle_big'), table_name='parking')
    op.drop_index(op.f('ix_parking_camera_id'), table_name='parking')
    op.drop_table('parking')
    # ### end Alembic commands ###
