"""add user_id into transaction

Revision ID: 0abbceea8f6c
Revises: 770de711d14a
Create Date: 2024-11-17 10:49:37.556129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abbceea8f6c'
down_revision = '770de711d14a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'user_id')
    # ### end Alembic commands ###
