"""empty message

Revision ID: 0d86c5440ccd
Revises: 86f7eff7a313
Create Date: 2024-04-09 11:14:17.273874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d86c5440ccd'
down_revision = '86f7eff7a313'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
