"""add column entrance_fee and hourly_fee in bill

Revision ID: 0e8cc191ac62
Revises: bfcafe7bcb08
Create Date: 2024-10-06 18:04:10.104906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8cc191ac62'
down_revision = 'bfcafe7bcb08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('entrance_fee', sa.Float(), nullable=True))
    op.add_column('bill', sa.Column('hourly_fee', sa.Float(), nullable=True))
    op.create_index(op.f('ix_bill_entrance_fee'), 'bill', ['entrance_fee'], unique=False)
    op.create_index(op.f('ix_bill_hourly_fee'), 'bill', ['hourly_fee'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_hourly_fee'), table_name='bill')
    op.drop_index(op.f('ix_bill_entrance_fee'), table_name='bill')
    op.drop_column('bill', 'hourly_fee')
    op.drop_column('bill', 'entrance_fee')
    # ### end Alembic commands ###
