"""parking

Revision ID: 112ab03ed0fd
Revises: 39f2313e7e15
Create Date: 2024-06-01 12:44:41.408181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112ab03ed0fd'
down_revision = '39f2313e7e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('brand_name', sa.String(length=50), nullable=True),
    sa.Column('floor_count', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('location_lat', sa.Float(precision=7), nullable=True),
    sa.Column('location_lon', sa.Float(precision=7), nullable=True),
    sa.Column('parking_address', sa.String(), nullable=True),
    sa.Column('parking_logo_base64', sa.String(), nullable=True),
    sa.Column('owner_first_name', sa.String(length=50), nullable=True),
    sa.Column('owner_last_name', sa.String(length=50), nullable=True),
    sa.Column('owner_national_id', sa.String(length=50), nullable=True),
    sa.Column('owner_postal_code', sa.String(length=50), nullable=True),
    sa.Column('owner_phone_number', sa.String(length=50), nullable=True),
    sa.Column('owner_email', sa.String(length=50), nullable=True),
    sa.Column('owner_sheba_number', sa.String(length=50), nullable=True),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.Column('owner_type', sa.Integer(), nullable=True),
    sa.Column('beneficiary_data', sa.JSON(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_created'), 'parking', ['created'], unique=False)
    op.create_index(op.f('ix_parking_id'), 'parking', ['id'], unique=False)
    op.create_index(op.f('ix_parking_is_deleted'), 'parking', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_parking_modified'), 'parking', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_modified'), table_name='parking')
    op.drop_index(op.f('ix_parking_is_deleted'), table_name='parking')
    op.drop_index(op.f('ix_parking_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_created'), table_name='parking')
    op.drop_table('parking')
    # ### end Alembic commands ###
