"""acl

Revision ID: 1558e7983cf1
Revises: 8080cf65fd30
Create Date: 2024-07-21 09:59:31.267795

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1558e7983cf1"
down_revision = "8080cf65fd30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE userroles AS ENUM ('SUPERADMIN', 'ADMIN_EQUIPMENT', 'ADMIN_USER', 'ADMIN_PRICE', 'ADMIN_ZONE_SPOT', 'ADMIN_PLATE_RECORD', 'READER_EQUIPMENT', 'READER_USER', 'READER_PRICE', 'READER_ZONE_SPOT', 'READER_PLATE_RECORD');"
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum(
                "SUPERADMIN",
                "ADMIN_EQUIPMENT",
                "ADMIN_USER",
                "ADMIN_PRICE",
                "ADMIN_ZONE_SPOT",
                "ADMIN_PLATE_RECORD",
                "READER_EQUIPMENT",
                "READER_USER",
                "READER_PRICE",
                "READER_ZONE_SPOT",
                "READER_PLATE_RECORD",
                name="userroles",
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("user", "role")
    op.execute("DROP TYPE userroles;")
    # ### end Alembic commands ###
