"""fix duplicate name table plate_detected

Revision ID: 17fb36974ca4
Revises: b7dc280f122d
Create Date: 2024-06-29 10:31:32.249065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fb36974ca4'
down_revision = 'b7dc280f122d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platedetected', sa.Column('plate', sa.String(), nullable=False))
    op.create_index(op.f('ix_platedetected_plate'), 'platedetected', ['plate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platedetected_plate'), table_name='platedetected')
    op.drop_column('platedetected', 'plate')
    # ### end Alembic commands ###
