"""add is_active into equipment

Revision ID: 201935381731
Revises: a55854b8021b
Create Date: 2024-11-25 14:18:39.981158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201935381731'
down_revision = 'a55854b8021b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'is_active')
    # ### end Alembic commands ###
