"""add table PaymentBill

Revision ID: 29c8009fedb0
Revises: 5de7b7e62655
Create Date: 2024-08-25 11:43:09.055388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c8009fedb0'
down_revision = '5de7b7e62655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentbill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentbill_bill_id'), 'paymentbill', ['bill_id'], unique=False)
    op.create_index(op.f('ix_paymentbill_created'), 'paymentbill', ['created'], unique=False)
    op.create_index(op.f('ix_paymentbill_id'), 'paymentbill', ['id'], unique=False)
    op.create_index(op.f('ix_paymentbill_is_deleted'), 'paymentbill', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_paymentbill_modified'), 'paymentbill', ['modified'], unique=False)
    op.create_index(op.f('ix_paymentbill_payment_id'), 'paymentbill', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentbill_payment_id'), table_name='paymentbill')
    op.drop_index(op.f('ix_paymentbill_modified'), table_name='paymentbill')
    op.drop_index(op.f('ix_paymentbill_is_deleted'), table_name='paymentbill')
    op.drop_index(op.f('ix_paymentbill_id'), table_name='paymentbill')
    op.drop_index(op.f('ix_paymentbill_created'), table_name='paymentbill')
    op.drop_index(op.f('ix_paymentbill_bill_id'), table_name='paymentbill')
    op.drop_table('paymentbill')
    # ### end Alembic commands ###
