"""change bill

Revision ID: 2bbc6bb98751
Revises: 4e5e472ba38c
Create Date: 2024-08-24 09:48:03.538251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbc6bb98751'
down_revision = '4e5e472ba38c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('issued_by', sa.String(), nullable=True))
    op.drop_index('ix_bill_status', table_name='bill')
    op.create_index(op.f('ix_bill_issued_by'), 'bill', ['issued_by'], unique=False)
    op.drop_column('bill', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bill_issued_by'), table_name='bill')
    op.create_index('ix_bill_status', 'bill', ['status'], unique=False)
    op.drop_column('bill', 'issued_by')
    # ### end Alembic commands ###
