"""add filed record_id into bill

Revision ID: 2bcfbc91ed4e
Revises: eccfb74d60bc
Create Date: 2024-08-31 08:50:23.583181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bcfbc91ed4e'
down_revision = 'eccfb74d60bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('record_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bill_record_id'), 'bill', ['record_id'], unique=False)
    op.create_foreign_key(None, 'bill', 'record', ['record_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill', type_='foreignkey')
    op.drop_index(op.f('ix_bill_record_id'), table_name='bill')
    op.drop_column('bill', 'record_id')
    # ### end Alembic commands ###
