"""change table name table ticket

Revision ID: 2d08b062ee73
Revises: 9830ad440a07
Create Date: 2024-10-22 12:56:51.940071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d08b062ee73'
down_revision = '9830ad440a07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('correct_plate', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_bill_id'), 'ticket', ['bill_id'], unique=False)
    op.create_index(op.f('ix_ticket_correct_plate'), 'ticket', ['correct_plate'], unique=False)
    op.create_index(op.f('ix_ticket_created'), 'ticket', ['created'], unique=False)
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_is_deleted'), 'ticket', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ticket_modified'), 'ticket', ['modified'], unique=False)
    op.create_index(op.f('ix_ticket_record_id'), 'ticket', ['record_id'], unique=False)
    op.create_index(op.f('ix_ticket_ticket_type'), 'ticket', ['ticket_type'], unique=False)
    op.create_index(op.f('ix_ticket_user_id'), 'ticket', ['user_id'], unique=False)
    op.drop_index('ix_error_bill_id', table_name='error')
    op.drop_index('ix_error_correct_plate', table_name='error')
    op.drop_index('ix_error_created', table_name='error')
    op.drop_index('ix_error_id', table_name='error')
    op.drop_index('ix_error_is_deleted', table_name='error')
    op.drop_index('ix_error_modified', table_name='error')
    op.drop_index('ix_error_record_id', table_name='error')
    op.drop_table('error')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correct_plate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='error_bill_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], name='error_record_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='error_pkey')
    )
    op.create_index('ix_error_record_id', 'error', ['record_id'], unique=False)
    op.create_index('ix_error_modified', 'error', ['modified'], unique=False)
    op.create_index('ix_error_is_deleted', 'error', ['is_deleted'], unique=False)
    op.create_index('ix_error_id', 'error', ['id'], unique=False)
    op.create_index('ix_error_created', 'error', ['created'], unique=False)
    op.create_index('ix_error_correct_plate', 'error', ['correct_plate'], unique=False)
    op.create_index('ix_error_bill_id', 'error', ['bill_id'], unique=False)
    op.drop_index(op.f('ix_ticket_user_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_ticket_type'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_record_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_modified'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_is_deleted'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_created'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_correct_plate'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_bill_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
