"""change_user_email_to_username

Revision ID: 2e3e3ad5fd3a
Revises: 46bc4703a244
Create Date: 2024-05-28 10:25:05.248538

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '2e3e3ad5fd3a'
down_revision = '46bc4703a244'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email', new_column_name='username')
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username', new_column_name='email')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_email', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
