"""column price_model in plate

Revision ID: 331633976966
Revises: bc8de10868ac
Create Date: 2024-05-08 11:25:25.943364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '331633976966'
down_revision = 'bc8de10868ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('price_model', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('plate', 'model_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('model_price', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('plate', 'price_model')
    # ### end Alembic commands ###
