"""add column additional_data into ticket

Revision ID: 39af89508414
Revises: a292adb31a6e
Create Date: 2024-10-23 11:38:54.127149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af89508414'
down_revision = 'a292adb31a6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('additional_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'additional_data')
    # ### end Alembic commands ###
