"""rename_parking_to_parkinglot

Revision ID: 39f2313e7e15
Revises: 2e3e3ad5fd3a
Create Date: 2024-05-29 11:33:59.353466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39f2313e7e15'
down_revision = '2e3e3ad5fd3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('parking', 'parkinglot')
    op.create_index(op.f('ix_parkinglot_camera_id'), 'parkinglot', ['camera_id'], unique=False)
    op.create_index(op.f('ix_parkinglot_coordinates_rectangle_big'), 'parkinglot', ['coordinates_rectangle_big'], unique=False)
    op.create_index(op.f('ix_parkinglot_coordinates_rectangle_small'), 'parkinglot', ['coordinates_rectangle_small'], unique=False)
    op.create_index(op.f('ix_parkinglot_created'), 'parkinglot', ['created'], unique=False)
    op.create_index(op.f('ix_parkinglot_id'), 'parkinglot', ['id'], unique=False)
    op.create_index(op.f('ix_parkinglot_is_deleted'), 'parkinglot', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_parkinglot_latest_time_modified'), 'parkinglot', ['latest_time_modified'], unique=False)
    op.create_index(op.f('ix_parkinglot_lpr_img_id'), 'parkinglot', ['lpr_img_id'], unique=False)
    op.create_index(op.f('ix_parkinglot_modified'), 'parkinglot', ['modified'], unique=False)
    op.create_index(op.f('ix_parkinglot_ocr_img_id'), 'parkinglot', ['ocr_img_id'], unique=False)
    op.create_index(op.f('ix_parkinglot_price_model_id'), 'parkinglot', ['price_model_id'], unique=False)
    op.drop_index('ix_parking_camera_id', table_name='parking')
    op.drop_index('ix_parking_coordinates_rectangle_big', table_name='parking')
    op.drop_index('ix_parking_coordinates_rectangle_small', table_name='parking')
    op.drop_index('ix_parking_created', table_name='parking')
    op.drop_index('ix_parking_id', table_name='parking')
    op.drop_index('ix_parking_is_deleted', table_name='parking')
    op.drop_index('ix_parking_latest_time_modified', table_name='parking')
    op.drop_index('ix_parking_lpr_img_id', table_name='parking')
    op.drop_index('ix_parking_modified', table_name='parking')
    op.drop_index('ix_parking_ocr_img_id', table_name='parking')
    op.drop_index('ix_parking_price_model_id', table_name='parking')

    op.alter_column('plate', 'name_parking', new_column_name='name_parkinglot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plate', 'name_parkinglot', new_column_name='name_parking')
    op.rename_table('parkinglot', 'parking')
    op.create_index('ix_parking_price_model_id', 'parking', ['price_model_id'], unique=False)
    op.create_index('ix_parking_ocr_img_id', 'parking', ['ocr_img_id'], unique=False)
    op.create_index('ix_parking_modified', 'parking', ['modified'], unique=False)
    op.create_index('ix_parking_lpr_img_id', 'parking', ['lpr_img_id'], unique=False)
    op.create_index('ix_parking_latest_time_modified', 'parking', ['latest_time_modified'], unique=False)
    op.create_index('ix_parking_is_deleted', 'parking', ['is_deleted'], unique=False)
    op.create_index('ix_parking_id', 'parking', ['id'], unique=False)
    op.create_index('ix_parking_created', 'parking', ['created'], unique=False)
    op.create_index('ix_parking_coordinates_rectangle_small', 'parking', ['coordinates_rectangle_small'], unique=False)
    op.create_index('ix_parking_coordinates_rectangle_big', 'parking', ['coordinates_rectangle_big'], unique=False)
    op.create_index('ix_parking_camera_id', 'parking', ['camera_id'], unique=False)
    op.drop_index(op.f('ix_parkinglot_price_model_id'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_ocr_img_id'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_modified'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_lpr_img_id'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_latest_time_modified'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_is_deleted'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_id'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_created'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_coordinates_rectangle_small'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_coordinates_rectangle_big'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_camera_id'), table_name='parkinglot')
    # ### end Alembic commands ###
