"""fix

Revision ID: 3c3539da3cdf
Revises: 464abf49d5ff
Create Date: 2024-11-10 16:16:05.803965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3539da3cdf'
down_revision = '464abf49d5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS userroles CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
