"""empty message

Revision ID: 3da388379c2a
Revises: 
Create Date: 2024-04-15 12:17:20.586423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da388379c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_created'), 'image', ['created'], unique=False)
    op.create_index(op.f('ix_image_is_deleted'), 'image', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_image_modified'), 'image', ['modified'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_deleted'), 'user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_modified'), 'user', ['modified'], unique=False)
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('camera_code', sa.String(), nullable=True),
    sa.Column('camera_ip', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_created'), 'camera', ['created'], unique=False)
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.create_index(op.f('ix_camera_image_id'), 'camera', ['image_id'], unique=False)
    op.create_index(op.f('ix_camera_is_deleted'), 'camera', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_camera_modified'), 'camera', ['modified'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('best_lpr_id', sa.Integer(), nullable=True),
    sa.Column('best_big_image_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_big_image_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['best_lpr_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_best_big_image_id'), 'record', ['best_big_image_id'], unique=False)
    op.create_index(op.f('ix_record_best_lpr_id'), 'record', ['best_lpr_id'], unique=False)
    op.create_index(op.f('ix_record_created'), 'record', ['created'], unique=False)
    op.create_index(op.f('ix_record_end_time'), 'record', ['end_time'], unique=False)
    op.create_index(op.f('ix_record_id'), 'record', ['id'], unique=False)
    op.create_index(op.f('ix_record_is_deleted'), 'record', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_record_modified'), 'record', ['modified'], unique=False)
    op.create_index(op.f('ix_record_ocr'), 'record', ['ocr'], unique=False)
    op.create_index(op.f('ix_record_score'), 'record', ['score'], unique=False)
    op.create_index(op.f('ix_record_start_time'), 'record', ['start_time'], unique=False)
    op.create_table('parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('floor_name', sa.String(), nullable=True),
    sa.Column('name_parking', sa.String(), nullable=True),
    sa.Column('percent_rotation_rectangle_small', sa.Integer(), nullable=True),
    sa.Column('percent_rotation_rectangle_big', sa.Integer(), nullable=True),
    sa.Column('coordinates_rectangle_big', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('coordinates_rectangle_small', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('number_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ocr', sa.String(), nullable=True),
    sa.Column('latest_time_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('ocr_img_id', sa.Integer(), nullable=True),
    sa.Column('lpr_img_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['lpr_img_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ocr_img_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_camera_id'), 'parking', ['camera_id'], unique=False)
    op.create_index(op.f('ix_parking_coordinates_rectangle_big'), 'parking', ['coordinates_rectangle_big'], unique=False)
    op.create_index(op.f('ix_parking_coordinates_rectangle_small'), 'parking', ['coordinates_rectangle_small'], unique=False)
    op.create_index(op.f('ix_parking_created'), 'parking', ['created'], unique=False)
    op.create_index(op.f('ix_parking_id'), 'parking', ['id'], unique=False)
    op.create_index(op.f('ix_parking_is_deleted'), 'parking', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_parking_latest_time_modified'), 'parking', ['latest_time_modified'], unique=False)
    op.create_index(op.f('ix_parking_lpr_img_id'), 'parking', ['lpr_img_id'], unique=False)
    op.create_index(op.f('ix_parking_modified'), 'parking', ['modified'], unique=False)
    op.create_index(op.f('ix_parking_ocr_img_id'), 'parking', ['ocr_img_id'], unique=False)
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr', sa.String(), nullable=True),
    sa.Column('lpr_id', sa.Integer(), nullable=True),
    sa.Column('big_image_id', sa.Integer(), nullable=True),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('number_line', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('floor_name', sa.String(), nullable=True),
    sa.Column('name_parking', sa.String(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['big_image_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['lpr_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_big_image_id'), 'plate', ['big_image_id'], unique=False)
    op.create_index(op.f('ix_plate_camera_id'), 'plate', ['camera_id'], unique=False)
    op.create_index(op.f('ix_plate_created'), 'plate', ['created'], unique=False)
    op.create_index(op.f('ix_plate_id'), 'plate', ['id'], unique=False)
    op.create_index(op.f('ix_plate_is_deleted'), 'plate', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plate_lpr_id'), 'plate', ['lpr_id'], unique=False)
    op.create_index(op.f('ix_plate_modified'), 'plate', ['modified'], unique=False)
    op.create_index(op.f('ix_plate_ocr'), 'plate', ['ocr'], unique=False)
    op.create_index(op.f('ix_plate_record_id'), 'plate', ['record_id'], unique=False)
    op.create_index(op.f('ix_plate_record_time'), 'plate', ['record_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_record_time'), table_name='plate')
    op.drop_index(op.f('ix_plate_record_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_ocr'), table_name='plate')
    op.drop_index(op.f('ix_plate_modified'), table_name='plate')
    op.drop_index(op.f('ix_plate_lpr_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_is_deleted'), table_name='plate')
    op.drop_index(op.f('ix_plate_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_created'), table_name='plate')
    op.drop_index(op.f('ix_plate_camera_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_big_image_id'), table_name='plate')
    op.drop_table('plate')
    op.drop_index(op.f('ix_parking_ocr_img_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_modified'), table_name='parking')
    op.drop_index(op.f('ix_parking_lpr_img_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_latest_time_modified'), table_name='parking')
    op.drop_index(op.f('ix_parking_is_deleted'), table_name='parking')
    op.drop_index(op.f('ix_parking_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_created'), table_name='parking')
    op.drop_index(op.f('ix_parking_coordinates_rectangle_small'), table_name='parking')
    op.drop_index(op.f('ix_parking_coordinates_rectangle_big'), table_name='parking')
    op.drop_index(op.f('ix_parking_camera_id'), table_name='parking')
    op.drop_table('parking')
    op.drop_index(op.f('ix_record_start_time'), table_name='record')
    op.drop_index(op.f('ix_record_score'), table_name='record')
    op.drop_index(op.f('ix_record_ocr'), table_name='record')
    op.drop_index(op.f('ix_record_modified'), table_name='record')
    op.drop_index(op.f('ix_record_is_deleted'), table_name='record')
    op.drop_index(op.f('ix_record_id'), table_name='record')
    op.drop_index(op.f('ix_record_end_time'), table_name='record')
    op.drop_index(op.f('ix_record_created'), table_name='record')
    op.drop_index(op.f('ix_record_best_lpr_id'), table_name='record')
    op.drop_index(op.f('ix_record_best_big_image_id'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_camera_modified'), table_name='camera')
    op.drop_index(op.f('ix_camera_is_deleted'), table_name='camera')
    op.drop_index(op.f('ix_camera_image_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_created'), table_name='camera')
    op.drop_table('camera')
    op.drop_index(op.f('ix_user_modified'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_image_modified'), table_name='image')
    op.drop_index(op.f('ix_image_is_deleted'), table_name='image')
    op.drop_index(op.f('ix_image_created'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
