"""fix datetime

Revision ID: 462d32d047f7
Revises: fc0cf1a4c2e6
Create Date: 2024-06-24 14:02:55.696861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462d32d047f7'
down_revision = 'fc0cf1a4c2e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
