"""delete payment and relation by bill add field status bill

Revision ID: 46461e3f86b5
Revises: cdfbb25f11b2
Create Date: 2024-09-07 16:14:34.819076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46461e3f86b5'
down_revision = 'cdfbb25f11b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_created', table_name='payment')
    op.drop_index('ix_payment_id', table_name='payment')
    op.drop_index('ix_payment_is_deleted', table_name='payment')
    op.drop_index('ix_payment_modified', table_name='payment')
    op.drop_index('ix_payment_price', table_name='payment')
    op.drop_index('ix_payment_status', table_name='payment')
    op.drop_index('ix_payment_tracking_code', table_name='payment')
    op.drop_constraint('paymentbill_payment_id_fkey', 'paymentbill', type_='foreignkey')
    op.drop_table('payment')
    op.drop_index('ix_paymentbill_bill_id', table_name='paymentbill')
    op.drop_index('ix_paymentbill_created', table_name='paymentbill')
    op.drop_index('ix_paymentbill_id', table_name='paymentbill')
    op.drop_index('ix_paymentbill_is_deleted', table_name='paymentbill')
    op.drop_index('ix_paymentbill_modified', table_name='paymentbill')
    op.drop_index('ix_paymentbill_payment_id', table_name='paymentbill')
    op.drop_table('paymentbill')
    op.add_column('bill', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_bill_status'), 'bill', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_status'), table_name='bill')
    op.drop_column('bill', 'status')
    op.create_table('paymentbill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], name='paymentbill_bill_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name='paymentbill_payment_id_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='paymentbill_pkey')
    )
    op.create_index('ix_paymentbill_payment_id', 'paymentbill', ['payment_id'], unique=False)
    op.create_index('ix_paymentbill_modified', 'paymentbill', ['modified'], unique=False)
    op.create_index('ix_paymentbill_is_deleted', 'paymentbill', ['is_deleted'], unique=False)
    op.create_index('ix_paymentbill_id', 'paymentbill', ['id'], unique=False)
    op.create_index('ix_paymentbill_created', 'paymentbill', ['created'], unique=False)
    op.create_index('ix_paymentbill_bill_id', 'paymentbill', ['bill_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tracking_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payment_pkey')
    )
    op.create_index('ix_payment_tracking_code', 'payment', ['tracking_code'], unique=False)
    op.create_index('ix_payment_status', 'payment', ['status'], unique=False)
    op.create_index('ix_payment_price', 'payment', ['price'], unique=False)
    op.create_index('ix_payment_modified', 'payment', ['modified'], unique=False)
    op.create_index('ix_payment_is_deleted', 'payment', ['is_deleted'], unique=False)
    op.create_index('ix_payment_id', 'payment', ['id'], unique=False)
    op.create_index('ix_payment_created', 'payment', ['created'], unique=False)
    # ### end Alembic commands ###
