"""fix

Revision ID: 464abf49d5ff
Revises: d78ddc5d33db
Create Date: 2024-11-10 16:09:46.591858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464abf49d5ff'
down_revision = 'd78ddc5d33db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE userroles CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
