"""fix type field price in model record

Revision ID: 4ab04d788d94
Revises: d821d1d0257b
Create Date: 2024-06-29 12:47:41.992273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ab04d788d94'
down_revision = 'd821d1d0257b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('price_model_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_record_price_model_id'), 'record', ['price_model_id'], unique=False)
    op.create_foreign_key(None, 'record', 'price', ['price_model_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('record', 'price_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('price_model', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_index(op.f('ix_record_price_model_id'), table_name='record')
    op.drop_column('record', 'price_model_id')
    # ### end Alembic commands ###
