"""fix nullable

Revision ID: 4c510f7764e1
Revises: 9b8e0ee6884e
Create Date: 2024-06-16 11:54:59.918447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c510f7764e1'
down_revision = '9b8e0ee6884e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plate', 'lpr_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('plate', 'big_image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plate', 'big_image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('plate', 'lpr_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
