"""new role

Revision ID: 4c6ca9d3e32a
Revises: 2bcfbc91ed4e
Create Date: 2024-08-31 12:14:09.974907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6ca9d3e32a'
down_revision = '2bcfbc91ed4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE userroles CASCADE;")
    op.execute(
        "CREATE TYPE userroles AS ENUM ('ADMINISTRATOR', 'PARKING_MANAGER', 'TECHNICAL_SUPPORT', 'OPERATIONAL_STAFF', 'REPORTING_ANALYSIS', 'SECURITY_STAFF', 'EXIT_GATE_DOOR');"
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum(
                "ADMINISTRATOR",
                "PARKING_MANAGER",
                "TECHNICAL_SUPPORT",
                "OPERATIONAL_STAFF",
                "REPORTING_ANALYSIS",
                "SECURITY_STAFF",
                "EXIT_GATE_DOOR",
                name="userroles",
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("user", "role")
    op.execute("DROP TYPE userroles;")
