"""save id image logo parking

Revision ID: 4f76bc0daff2
Revises: ff9a82797575
Create Date: 2024-07-24 15:26:23.630761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f76bc0daff2'
down_revision = 'ff9a82797575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('parking_logo_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parking', 'image', ['parking_logo_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('parking', 'parking_logo_base64')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('parking_logo_base64', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_column('parking', 'parking_logo_image_id')
    # ### end Alembic commands ###
