"""sqlaclchemy2 model plate

Revision ID: 50d734d2441f
Revises: f1b47924e868
Create Date: 2024-04-30 12:27:11.578916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d734d2441f'
down_revision = 'f1b47924e868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr', sa.String(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number_line', sa.Integer(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(), nullable=False),
    sa.Column('name_parking', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('lpr_id', sa.Integer(), nullable=False),
    sa.Column('big_image_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['big_image_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['lpr_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_big_image_id'), 'plate', ['big_image_id'], unique=False)
    op.create_index(op.f('ix_plate_camera_id'), 'plate', ['camera_id'], unique=False)
    op.create_index(op.f('ix_plate_created'), 'plate', ['created'], unique=False)
    op.create_index(op.f('ix_plate_id'), 'plate', ['id'], unique=False)
    op.create_index(op.f('ix_plate_is_deleted'), 'plate', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plate_lpr_id'), 'plate', ['lpr_id'], unique=False)
    op.create_index(op.f('ix_plate_modified'), 'plate', ['modified'], unique=False)
    op.create_index(op.f('ix_plate_ocr'), 'plate', ['ocr'], unique=False)
    op.create_index(op.f('ix_plate_record_id'), 'plate', ['record_id'], unique=False)
    op.create_index(op.f('ix_plate_record_time'), 'plate', ['record_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_record_time'), table_name='plate')
    op.drop_index(op.f('ix_plate_record_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_ocr'), table_name='plate')
    op.drop_index(op.f('ix_plate_modified'), table_name='plate')
    op.drop_index(op.f('ix_plate_lpr_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_is_deleted'), table_name='plate')
    op.drop_index(op.f('ix_plate_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_created'), table_name='plate')
    op.drop_index(op.f('ix_plate_camera_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_big_image_id'), table_name='plate')
    op.drop_table('plate')
    # ### end Alembic commands ###
