"""fix name and add column verifiy and request user in to ticket

Revision ID: 520f8e7cccd3
Revises: 39af89508414
Create Date: 2024-10-23 11:54:35.675739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520f8e7cccd3'
down_revision = '39af89508414'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('requesting_user_id', sa.Integer(), nullable=True))
    op.add_column('ticket', sa.Column('verifying_user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_ticket_user_id', table_name='ticket')
    op.create_index(op.f('ix_ticket_requesting_user_id'), 'ticket', ['requesting_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_verifying_user_id'), 'ticket', ['verifying_user_id'], unique=False)
    op.drop_constraint('ticket_user_id_fkey', 'ticket', type_='foreignkey')
    op.create_foreign_key(None, 'ticket', 'user', ['verifying_user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'ticket', 'user', ['requesting_user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('ticket', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.drop_constraint(None, 'ticket', type_='foreignkey')
    op.create_foreign_key('ticket_user_id_fkey', 'ticket', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_ticket_verifying_user_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_requesting_user_id'), table_name='ticket')
    op.create_index('ix_ticket_user_id', 'ticket', ['user_id'], unique=False)
    op.drop_column('ticket', 'verifying_user_id')
    op.drop_column('ticket', 'requesting_user_id')
    # ### end Alembic commands ###
