"""rule_add_weekdays_field

Revision ID: 5431213bf91b
Revises: a475a832b2f1
Create Date: 2024-06-12 13:23:55.042457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5431213bf91b'
down_revision = 'a475a832b2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule', sa.Column('weekdays', postgresql.ARRAY(sa.Integer()), nullable=False, server_default="{}"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule', 'weekdays')
    # ### end Alembic commands ###
