"""fix relations

Revision ID: 58b539025179
Revises: 61086cc52c04
Create Date: 2024-09-08 12:05:05.614433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b539025179'
down_revision = '61086cc52c04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bill_name_zone', table_name='bill')
    op.drop_constraint('uq_bill_number', 'bill', type_='unique')
    op.drop_column('bill', 'name_zone')
    op.drop_index('ix_event_price_model_id', table_name='event')
    op.drop_constraint('event_price_model_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'price_model_id')
    op.add_column('image', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_image_camera_id'), 'image', ['camera_id'], unique=False)
    op.create_foreign_key('fk_image_camera_id', 'image', 'equipment', ['camera_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('image_camera_id_fkey', 'image', type_='foreignkey')
    op.drop_index(op.f('ix_image_camera_id'), table_name='image')
    op.drop_column('image', 'camera_id')
    op.add_column('event', sa.Column('price_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('event_price_model_id_fkey', 'event', 'price', ['price_model_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index('ix_event_price_model_id', 'event', ['price_model_id'], unique=False)
    op.add_column('bill', sa.Column('name_zone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_bill_number', 'bill', ['bill_number'])
    op.create_index('ix_bill_name_zone', 'bill', ['name_zone'], unique=False)
    # ### end Alembic commands ###
