"""table payment

Revision ID: 5de7b7e62655
Revises: 2bbc6bb98751
Create Date: 2024-08-24 14:37:27.632607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de7b7e62655'
down_revision = '2bbc6bb98751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tracking_code', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_bill_id'), 'payment', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payment_created'), 'payment', ['created'], unique=False)
    op.create_index(op.f('ix_payment_id'), 'payment', ['id'], unique=False)
    op.create_index(op.f('ix_payment_is_deleted'), 'payment', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_modified'), 'payment', ['modified'], unique=False)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_index(op.f('ix_payment_tracking_code'), 'payment', ['tracking_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_tracking_code'), table_name='payment')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_modified'), table_name='payment')
    op.drop_index(op.f('ix_payment_is_deleted'), table_name='payment')
    op.drop_index(op.f('ix_payment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_created'), table_name='payment')
    op.drop_index(op.f('ix_payment_bill_id'), table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
