"""delete column status into plate

Revision ID: 5f3b1cc46f41
Revises: 2fd483278b5a
Create Date: 2024-11-03 12:03:45.298537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3b1cc46f41'
down_revision = '2fd483278b5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platelist_status', table_name='platelist')
    op.drop_column('platelist', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platelist', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_platelist_status', 'platelist', ['status'], unique=False)
    # ### end Alembic commands ###
