"""update table bill

Revision ID: 61086cc52c04
Revises: c188c10c53d2
Create Date: 2024-09-08 11:39:10.185111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61086cc52c04'
down_revision = 'c188c10c53d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SEQUENCE bill_number_seq START 1000 INCREMENT 1'))
    op.add_column('bill', sa.Column('bill_number', sa.Integer(), server_default=sa.text("nextval('bill_number_seq')"), nullable=False))
    op.add_column('bill', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('img_entrance_id', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('img_exit_id', sa.Integer(), nullable=True))
    op.add_column('bill', sa.Column('name_zone', sa.String(), nullable=True))
    op.create_index(op.f('ix_bill_bill_number'), 'bill', ['bill_number'], unique=True)
    op.create_index(op.f('ix_bill_name_zone'), 'bill', ['name_zone'], unique=False)
    op.create_index(op.f('ix_bill_zone_id'), 'bill', ['zone_id'], unique=False)
    op.create_foreign_key('fk_bill_zone_id', 'bill', 'zone', ['zone_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_unique_constraint('uq_bill_number', 'bill', ['bill_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bill_zone_id', 'bill', type_='foreignkey')
    op.drop_index(op.f('ix_bill_zone_id'), table_name='bill')
    op.drop_index(op.f('ix_bill_name_zone'), table_name='bill')
    op.drop_index(op.f('ix_bill_bill_number'), table_name='bill')
    op.drop_column('bill', 'name_zone')
    op.drop_column('bill', 'img_exit_id')
    op.drop_column('bill', 'img_entrance_id')
    op.drop_column('bill', 'zone_id')
    op.drop_column('bill', 'bill_number')
    op.drop_constraint('uq_bill_number', 'bill', type_='unique')
    op.execute(sa.text('DROP SEQUENCE bill_number_seq'))
    # ### end Alembic commands ###