"""cahnge user_id to user_paid_id into bill

Revision ID: 639b56f942d9
Revises: 9feabae93fb1
Create Date: 2024-11-30 12:36:10.214254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639b56f942d9'
down_revision = '9feabae93fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('user_paid_id', sa.Integer(), nullable=True))
    op.drop_index('ix_bill_user_id', table_name='bill')
    op.create_index(op.f('ix_bill_user_paid_id'), 'bill', ['user_paid_id'], unique=False)
    op.drop_constraint('bill_user_id_fkey', 'bill', type_='foreignkey')
    op.create_foreign_key(None, 'bill', 'user', ['user_paid_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('bill', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bill', type_='foreignkey')
    op.create_foreign_key('bill_user_id_fkey', 'bill', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_bill_user_paid_id'), table_name='bill')
    op.create_index('ix_bill_user_id', 'bill', ['user_id'], unique=False)
    op.drop_column('bill', 'user_paid_id')
    # ### end Alembic commands ###
