"""fix name

Revision ID: 69cbf715e445
Revises: 7607e5838d70
Create Date: 2024-08-10 19:07:53.352681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69cbf715e445'
down_revision = '7607e5838d70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price_model', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('price', 'model_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('model_price', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('price', 'price_model')
    # ### end Alembic commands ###
