"""add column to bill

Revision ID: 704c1014a373
Revises: 58b539025179
Create Date: 2024-09-13 17:02:24.791465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704c1014a373'
down_revision = '58b539025179'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('rrn_number', sa.String(), nullable=True))
    op.add_column('bill', sa.Column('time_paid', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_bill_rrn_number'), 'bill', ['rrn_number'], unique=False)
    op.create_index(op.f('ix_bill_time_paid'), 'bill', ['time_paid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_time_paid'), table_name='bill')
    op.drop_index(op.f('ix_bill_rrn_number'), table_name='bill')
    op.drop_column('bill', 'time_paid')
    op.drop_column('bill', 'rrn_number')
    # ### end Alembic commands ###
