"""change role acl

Revision ID: 71761356f420
Revises: 4f76bc0daff2
Create Date: 2024-07-28 12:49:57.836250

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71761356f420"
down_revision = "4f76bc0daff2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE userroles;")
    op.execute(
        "CREATE TYPE userroles AS ENUM ('ADMINISTRATOR', 'PARKING_MANAGER', 'TECHNICAL_SUPPORT', 'OPERATIONAL_STAFF', 'REPORTING_ANALYSIS', 'SECURITY_STAFF');"
    )
    op.add_column(
        "user",
        sa.Column(
            "role",
            sa.Enum(
                "ADMINISTRATOR",
                "PARKING_MANAGER",
                "TECHNICAL_SUPPORT",
                "OPERATIONAL_STAFF",
                "REPORTING_ANALYSIS",
                "SECURITY_STAFF",
                name="userroles",
            ),
            nullable=True,
        ),
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_column("user", "role")
    op.execute("DROP TYPE userroles;")
