"""model_camera

Revision ID: 73daf68b84ba
Revises: 062b54e831e6
Create Date: 2024-04-16 11:46:13.466389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73daf68b84ba'
down_revision = '062b54e831e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('camera_code', sa.String(), nullable=True),
    sa.Column('camera_ip', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camera_created'), 'camera', ['created'], unique=False)
    op.create_index(op.f('ix_camera_id'), 'camera', ['id'], unique=False)
    op.create_index(op.f('ix_camera_image_id'), 'camera', ['image_id'], unique=False)
    op.create_index(op.f('ix_camera_is_deleted'), 'camera', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_camera_modified'), 'camera', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_camera_modified'), table_name='camera')
    op.drop_index(op.f('ix_camera_is_deleted'), table_name='camera')
    op.drop_index(op.f('ix_camera_image_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_id'), table_name='camera')
    op.drop_index(op.f('ix_camera_created'), table_name='camera')
    op.drop_table('camera')
    # ### end Alembic commands ###
