"""fix price

Revision ID: 7607e5838d70
Revises: 433b7513ea3b
Create Date: 2024-08-10 16:46:34.224933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7607e5838d70'
down_revision = '433b7513ea3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('model_price', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('price', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('model', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('price', 'model_price')
    # ### end Alembic commands ###
