"""equipment_zone_id

Revision ID: 79ff4f7d50b0
Revises: 0065a55c09bc
Create Date: 2024-06-08 15:05:47.731001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ff4f7d50b0'
down_revision = '0065a55c09bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'parkingzone', ['zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'zone_id')
    # ### end Alembic commands ###
