"""fix relation payment

Revision ID: 840f5de47436
Revises: 29c8009fedb0
Create Date: 2024-08-25 12:29:39.574395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840f5de47436'
down_revision = '29c8009fedb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_bill_id', table_name='payment')
    op.drop_constraint('payment_bill_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'bill_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_bill_id_fkey', 'payment', 'bill', ['bill_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_index('ix_payment_bill_id', 'payment', ['bill_id'], unique=False)
    # ### end Alembic commands ###
