"""fix name field parkinglot_id in model record

Revision ID: 868ed1cbae16
Revises: 4ab04d788d94
Create Date: 2024-06-29 12:56:42.681269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868ed1cbae16'
down_revision = '4ab04d788d94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('parkinglot_id', sa.Integer(), nullable=True))
    op.drop_index('ix_record_parking_lot_id', table_name='record')
    op.create_index(op.f('ix_record_parkinglot_id'), 'record', ['parkinglot_id'], unique=False)
    op.drop_constraint('record_parking_lot_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'parkinglot', ['parkinglot_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('record', 'parking_lot_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('parking_lot_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_parking_lot_id_fkey', 'record', 'parkinglot', ['parking_lot_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_record_parkinglot_id'), table_name='record')
    op.create_index('ix_record_parking_lot_id', 'record', ['parking_lot_id'], unique=False)
    op.drop_column('record', 'parkinglot_id')
    # ### end Alembic commands ###
