"""add column invalid into event

Revision ID: 884ff520533a
Revises: 37d5b7f39a39
Create Date: 2024-10-20 19:12:47.232275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884ff520533a'
down_revision = '37d5b7f39a39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('invalid', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_event_invalid'), 'event', ['invalid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_invalid'), table_name='event')
    op.drop_column('event', 'invalid')
    # ### end Alembic commands ###
