"""empty message

Revision ID: 890f63cf262f
Revises: 73a04908d735
Create Date: 2024-06-02 16:10:08.212486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890f63cf262f'
down_revision = '73a04908d735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking', 'location_lat',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=True)
    op.alter_column('parking', 'location_lon',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking', 'location_lon',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('parking', 'location_lat',
               existing_type=sa.Float(precision=7),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
