"""create table price

Revision ID: 939fc994283a
Revises: c150b98fe13d
Create Date: 2024-05-07 13:06:46.140007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939fc994283a'
down_revision = 'c150b98fe13d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'name_fa',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('price', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('price', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('price', 'name_fa',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
