"""refactor model parkinglot

Revision ID: 975642ca3129
Revises: 17fb36974ca4
Create Date: 2024-06-29 11:46:46.145732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975642ca3129'
down_revision = '17fb36974ca4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkinglot', sa.Column('plate_image_id', sa.Integer(), nullable=True))
    op.add_column('parkinglot', sa.Column('lpr_image_id', sa.Integer(), nullable=True))
    op.drop_index('ix_parkinglot_lpr_img_id', table_name='parkinglot')
    op.drop_index('ix_parkinglot_ocr_img_id', table_name='parkinglot')
    op.create_index(op.f('ix_parkinglot_lpr_image_id'), 'parkinglot', ['lpr_image_id'], unique=False)
    op.create_index(op.f('ix_parkinglot_plate_image_id'), 'parkinglot', ['plate_image_id'], unique=False)
    op.drop_constraint('parking_ocr_img_id_fkey', 'parkinglot', type_='foreignkey')
    op.drop_constraint('parking_lpr_img_id_fkey', 'parkinglot', type_='foreignkey')
    op.create_foreign_key(None, 'parkinglot', 'image', ['plate_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'parkinglot', 'image', ['lpr_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('parkinglot', 'ocr_img_id')
    op.drop_column('parkinglot', 'lpr_img_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkinglot', sa.Column('lpr_img_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('parkinglot', sa.Column('ocr_img_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parkinglot', type_='foreignkey')
    op.drop_constraint(None, 'parkinglot', type_='foreignkey')
    op.create_foreign_key('parking_lpr_img_id_fkey', 'parkinglot', 'image', ['lpr_img_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('parking_ocr_img_id_fkey', 'parkinglot', 'image', ['ocr_img_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_parkinglot_plate_image_id'), table_name='parkinglot')
    op.drop_index(op.f('ix_parkinglot_lpr_image_id'), table_name='parkinglot')
    op.create_index('ix_parkinglot_ocr_img_id', 'parkinglot', ['ocr_img_id'], unique=False)
    op.create_index('ix_parkinglot_lpr_img_id', 'parkinglot', ['lpr_img_id'], unique=False)
    op.drop_column('parkinglot', 'lpr_image_id')
    op.drop_column('parkinglot', 'plate_image_id')
    # ### end Alembic commands ###
