"""table error

Revision ID: 9830ad440a07
Revises: 217829808cec
Create Date: 2024-10-21 16:49:48.686306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9830ad440a07'
down_revision = '217829808cec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('correct_plate', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_bill_id'), 'error', ['bill_id'], unique=False)
    op.create_index(op.f('ix_error_correct_plate'), 'error', ['correct_plate'], unique=False)
    op.create_index(op.f('ix_error_created'), 'error', ['created'], unique=False)
    op.create_index(op.f('ix_error_id'), 'error', ['id'], unique=False)
    op.create_index(op.f('ix_error_is_deleted'), 'error', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_error_modified'), 'error', ['modified'], unique=False)
    op.create_index(op.f('ix_error_record_id'), 'error', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_record_id'), table_name='error')
    op.drop_index(op.f('ix_error_modified'), table_name='error')
    op.drop_index(op.f('ix_error_is_deleted'), table_name='error')
    op.drop_index(op.f('ix_error_id'), table_name='error')
    op.drop_index(op.f('ix_error_created'), table_name='error')
    op.drop_index(op.f('ix_error_correct_plate'), table_name='error')
    op.drop_index(op.f('ix_error_bill_id'), table_name='error')
    op.drop_table('error')
    # ### end Alembic commands ###
