"""add column user_id into bill

Revision ID: 9feabae93fb1
Revises: ee554e14f560
Create Date: 2024-11-30 12:19:25.898736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9feabae93fb1'
down_revision = 'ee554e14f560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bill_user_id'), 'bill', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bill', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill', type_='foreignkey')
    op.drop_index(op.f('ix_bill_user_id'), table_name='bill')
    op.drop_column('bill', 'user_id')
    # ### end Alembic commands ###
