"""add column status and change name column into ticket

Revision ID: a292adb31a6e
Revises: 2d08b062ee73
Create Date: 2024-10-22 13:22:42.110468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a292adb31a6e'
down_revision = '2d08b062ee73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('type', sa.String(), nullable=True))
    op.add_column('ticket', sa.Column('status', sa.String(), nullable=True))
    op.drop_index('ix_ticket_ticket_type', table_name='ticket')
    op.create_index(op.f('ix_ticket_status'), 'ticket', ['status'], unique=False)
    op.create_index(op.f('ix_ticket_type'), 'ticket', ['type'], unique=False)
    op.drop_column('ticket', 'ticket_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('ticket_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ticket_type'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_status'), table_name='ticket')
    op.create_index('ix_ticket_ticket_type', 'ticket', ['ticket_type'], unique=False)
    op.drop_column('ticket', 'status')
    op.drop_column('ticket', 'type')
    # ### end Alembic commands ###
