"""rule_table

Revision ID: a475a832b2f1
Revises: cac97816ab88
Create Date: 2024-06-11 11:57:25.123401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475a832b2f1'
down_revision = 'cac97816ab88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_fa', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('registeration_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_created'), 'rule', ['created'], unique=False)
    op.create_index(op.f('ix_rule_id'), 'rule', ['id'], unique=False)
    op.create_index(op.f('ix_rule_is_deleted'), 'rule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rule_modified'), 'rule', ['modified'], unique=False)
    op.create_table('platerule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platerule_created'), 'platerule', ['created'], unique=False)
    op.create_index(op.f('ix_platerule_id'), 'platerule', ['id'], unique=False)
    op.create_index(op.f('ix_platerule_is_deleted'), 'platerule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_platerule_modified'), 'platerule', ['modified'], unique=False)
    op.create_table('zonerule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rule.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['parkingzone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonerule_created'), 'zonerule', ['created'], unique=False)
    op.create_index(op.f('ix_zonerule_id'), 'zonerule', ['id'], unique=False)
    op.create_index(op.f('ix_zonerule_is_deleted'), 'zonerule', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_zonerule_modified'), 'zonerule', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zonerule_modified'), table_name='zonerule')
    op.drop_index(op.f('ix_zonerule_is_deleted'), table_name='zonerule')
    op.drop_index(op.f('ix_zonerule_id'), table_name='zonerule')
    op.drop_index(op.f('ix_zonerule_created'), table_name='zonerule')
    op.drop_table('zonerule')
    op.drop_index(op.f('ix_platerule_modified'), table_name='platerule')
    op.drop_index(op.f('ix_platerule_is_deleted'), table_name='platerule')
    op.drop_index(op.f('ix_platerule_id'), table_name='platerule')
    op.drop_index(op.f('ix_platerule_created'), table_name='platerule')
    op.drop_table('platerule')
    op.drop_index(op.f('ix_rule_modified'), table_name='rule')
    op.drop_index(op.f('ix_rule_is_deleted'), table_name='rule')
    op.drop_index(op.f('ix_rule_id'), table_name='rule')
    op.drop_index(op.f('ix_rule_created'), table_name='rule')
    op.drop_table('rule')
    # ### end Alembic commands ###
