"""set camera_id in event nullable true

Revision ID: a50c89cf5aca
Revises: ce576526cf91
Create Date: 2024-10-02 12:38:57.852837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50c89cf5aca'
down_revision = 'ce576526cf91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'camera_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
