"""add text and type into notifications

Revision ID: a55854b8021b
Revises: 087eecd32228
Create Date: 2024-11-25 12:25:01.638216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55854b8021b'
down_revision = '087eecd32228'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('text', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('type_notice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type_notice')
    op.drop_column('notifications', 'text')
    # ### end Alembic commands ###
