"""capacity zone

Revision ID: a7c47dbd2ad5
Revises: 2e3a3aecbb28
Create Date: 2024-07-30 10:20:12.768739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c47dbd2ad5'
down_revision = '2e3a3aecbb28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'capacity')
    # ### end Alembic commands ###
