"""refactor model

Revision ID: ac4924b0a38d
Revises: 557725f0cff5
Create Date: 2024-06-24 12:11:43.876918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4924b0a38d'
down_revision = '557725f0cff5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platedetected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('parkinglot_id', sa.Integer(), nullable=True),
    sa.Column('name_parkinglot', sa.String(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('lpr_id', sa.Integer(), nullable=True),
    sa.Column('big_image_id', sa.Integer(), nullable=True),
    sa.Column('price_model_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['big_image_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['lpr_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parkinglot_id'], ['parkinglot.id'], ),
    sa.ForeignKeyConstraint(['price_model_id'], ['price.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['parkingzone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platedetected_big_image_id'), 'platedetected', ['big_image_id'], unique=False)
    op.create_index(op.f('ix_platedetected_camera_id'), 'platedetected', ['camera_id'], unique=False)
    op.create_index(op.f('ix_platedetected_created'), 'platedetected', ['created'], unique=False)
    op.create_index(op.f('ix_platedetected_id'), 'platedetected', ['id'], unique=False)
    op.create_index(op.f('ix_platedetected_is_deleted'), 'platedetected', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_platedetected_lpr_id'), 'platedetected', ['lpr_id'], unique=False)
    op.create_index(op.f('ix_platedetected_modified'), 'platedetected', ['modified'], unique=False)
    op.create_index(op.f('ix_platedetected_parkinglot_id'), 'platedetected', ['parkinglot_id'], unique=False)
    op.create_index(op.f('ix_platedetected_plate'), 'platedetected', ['plate'], unique=False)
    op.create_index(op.f('ix_platedetected_price_model_id'), 'platedetected', ['price_model_id'], unique=False)
    op.create_index(op.f('ix_platedetected_record_id'), 'platedetected', ['record_id'], unique=False)
    op.create_index(op.f('ix_platedetected_record_time'), 'platedetected', ['record_time'], unique=False)
    op.create_index(op.f('ix_platedetected_zone_id'), 'platedetected', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platedetected_zone_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_record_time'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_record_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_price_model_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_plate'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_parkinglot_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_modified'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_lpr_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_is_deleted'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_created'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_camera_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_big_image_id'), table_name='platedetected')
    op.drop_table('platedetected')
    # ### end Alembic commands ###
