"""fix nullable in record_id in plate

Revision ID: b2c3766591fe
Revises: 331633976966
Create Date: 2024-05-08 11:27:23.372199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3766591fe'
down_revision = '331633976966'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plate', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plate', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
