"""add column additional_data into image

Revision ID: b5c232512d2a
Revises: 59f7c022987b
Create Date: 2024-10-30 14:44:22.775095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5c232512d2a'
down_revision = '59f7c022987b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.drop_column('image', 'additonal_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('additonal_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('image', 'additional_data')
    # ### end Alembic commands ###
