"""refactor table plate_detected

Revision ID: b7dc280f122d
Revises: 462d32d047f7
Create Date: 2024-06-29 10:11:51.935321

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7dc280f122d'
down_revision = '462d32d047f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platedetected', sa.Column('plate_image_id', sa.Integer(), nullable=True))
    op.add_column('platedetected', sa.Column('lpr_image_id', sa.Integer(), nullable=True))
    op.drop_index('ix_platedetected_big_image_id', table_name='platedetected')
    op.drop_index('ix_platedetected_lpr_id', table_name='platedetected')
    op.drop_index('ix_platedetected_plate', table_name='platedetected')
    op.create_index(op.f('ix_platedetected_lpr_image_id'), 'platedetected', ['lpr_image_id'], unique=False)
    op.create_index(op.f('ix_platedetected_plate_image_id'), 'platedetected', ['plate_image_id'], unique=False)
    op.drop_constraint('platedetected_lpr_id_fkey', 'platedetected', type_='foreignkey')
    op.drop_constraint('platedetected_big_image_id_fkey', 'platedetected', type_='foreignkey')
    op.create_foreign_key(None, 'platedetected', 'image', ['plate_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'platedetected', 'image', ['lpr_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('platedetected', 'big_image_id')
    op.drop_column('platedetected', 'name_parkinglot')
    op.drop_column('platedetected', 'lpr_id')
    op.drop_column('platedetected', 'plate')
    op.alter_column('price', 'expiration_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_price_expiration_datetime'), 'price', ['expiration_datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_expiration_datetime'), table_name='price')
    op.alter_column('price', 'expiration_datetime',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('platedetected', sa.Column('plate', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('platedetected', sa.Column('lpr_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('platedetected', sa.Column('name_parkinglot', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('platedetected', sa.Column('big_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'platedetected', type_='foreignkey')
    op.drop_constraint(None, 'platedetected', type_='foreignkey')
    op.create_foreign_key('platedetected_big_image_id_fkey', 'platedetected', 'image', ['big_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('platedetected_lpr_id_fkey', 'platedetected', 'image', ['lpr_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_platedetected_plate_image_id'), table_name='platedetected')
    op.drop_index(op.f('ix_platedetected_lpr_image_id'), table_name='platedetected')
    op.create_index('ix_platedetected_plate', 'platedetected', ['plate'], unique=False)
    op.create_index('ix_platedetected_lpr_id', 'platedetected', ['lpr_id'], unique=False)
    op.create_index('ix_platedetected_big_image_id', 'platedetected', ['big_image_id'], unique=False)
    op.drop_column('platedetected', 'lpr_image_id')
    op.drop_column('platedetected', 'plate_image_id')
    # ### end Alembic commands ###
