"""column model price in plate

Revision ID: bc8de10868ac
Revises: e90e61a40771
Create Date: 2024-05-08 11:15:33.347016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc8de10868ac'
down_revision = 'e90e61a40771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('model_price', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plate', 'model_price')
    # ### end Alembic commands ###
