"""extend order id

Revision ID: be2e7debdfda
Revises: 430cd0aa407b
Create Date: 2024-11-18 18:07:27.523569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2e7debdfda'
down_revision = '430cd0aa407b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('order_id_paymet_switch', sa.BigInteger(), nullable=True))
    op.add_column('transaction', sa.Column('order_id_b2b', sa.BigInteger(), nullable=True))
    op.add_column('transaction', sa.Column('rrn', sa.String(), nullable=True))
    op.drop_constraint('transaction_order_id_key', 'transaction', type_='unique')
    op.create_unique_constraint(None, 'transaction', ['order_id_b2b'])
    op.create_unique_constraint(None, 'transaction', ['order_id_paymet_switch'])
    op.drop_column('transaction', 'order_id')
    op.drop_column('transaction', 'rrn_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('rrn_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transaction', sa.Column('order_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_constraint(None, 'transaction', type_='unique')
    op.create_unique_constraint('transaction_order_id_key', 'transaction', ['order_id'])
    op.drop_column('transaction', 'rrn')
    op.drop_column('transaction', 'order_id_b2b')
    op.drop_column('transaction', 'order_id_paymet_switch')
    # ### end Alembic commands ###
