"""lat_lon_float_to_numeric

Revision ID: bf2bae3498fe
Revises: 462f5e2cb45b
Create Date: 2024-06-09 10:36:31.092964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2bae3498fe'
down_revision = '462f5e2cb45b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking', 'location_lat',
               existing_type=sa.REAL(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    op.alter_column('parking', 'location_lon',
               existing_type=sa.REAL(),
               type_=sa.NUMERIC(precision=10, scale=7),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parking', 'location_lon',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('parking', 'location_lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
