"""table plate black white list

Revision ID: c0d9bd429260
Revises: 520f8e7cccd3
Create Date: 2024-10-29 14:15:15.790407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d9bd429260'
down_revision = '520f8e7cccd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=True),
    sa.Column('expire_start', sa.DateTime(), nullable=False),
    sa.Column('expire_end', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platelist_created'), 'platelist', ['created'], unique=False)
    op.create_index(op.f('ix_platelist_expire_end'), 'platelist', ['expire_end'], unique=False)
    op.create_index(op.f('ix_platelist_expire_start'), 'platelist', ['expire_start'], unique=False)
    op.create_index(op.f('ix_platelist_id'), 'platelist', ['id'], unique=False)
    op.create_index(op.f('ix_platelist_is_deleted'), 'platelist', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_platelist_modified'), 'platelist', ['modified'], unique=False)
    op.create_index(op.f('ix_platelist_name'), 'platelist', ['name'], unique=False)
    op.create_index(op.f('ix_platelist_plate'), 'platelist', ['plate'], unique=True)
    op.create_index(op.f('ix_platelist_status'), 'platelist', ['status'], unique=False)
    op.create_index(op.f('ix_platelist_type'), 'platelist', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platelist_type'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_status'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_plate'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_name'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_modified'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_is_deleted'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_id'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_expire_start'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_expire_end'), table_name='platelist')
    op.drop_index(op.f('ix_platelist_created'), table_name='platelist')
    op.drop_table('platelist')
    # ### end Alembic commands ###
