"""type camera

Revision ID: c10045cd4f2d
Revises: a7c47dbd2ad5
Create Date: 2024-07-30 12:03:37.302057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c10045cd4f2d'
down_revision = 'a7c47dbd2ad5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('type_camera', sa.String(), nullable=True))
    op.drop_column('plate', 'type_status_spot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plate', sa.Column('type_status_spot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('plate', 'type_camera')
    # ### end Alembic commands ###
