"""create table price

Revision ID: c150b98fe13d
Revises: 414c16dd262c
Create Date: 2024-05-07 13:04:29.789661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c150b98fe13d'
down_revision = '414c16dd262c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('name_fa', sa.String(length=50), nullable=False))
    op.add_column('price', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'name')
    op.drop_column('price', 'name_fa')
    # ### end Alembic commands ###
