"""update table record

Revision ID: c188c10c53d2
Revises: 46461e3f86b5
Create Date: 2024-09-07 19:35:40.585763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c188c10c53d2'
down_revision = '46461e3f86b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('img_entrance_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('img_exit_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('img_plate_entrance_id', sa.Integer(), nullable=True))
    op.add_column('record', sa.Column('img_plate_exit_id', sa.Integer(), nullable=True))
    op.drop_index('ix_record_best_lpr_image_id', table_name='record')
    op.drop_index('ix_record_best_plate_image_id', table_name='record')
    op.drop_index('ix_record_price_model_id', table_name='record')
    op.create_index(op.f('ix_record_img_entrance_id'), 'record', ['img_entrance_id'], unique=False)
    op.create_index(op.f('ix_record_img_exit_id'), 'record', ['img_exit_id'], unique=False)
    op.create_index(op.f('ix_record_img_plate_entrance_id'), 'record', ['img_plate_entrance_id'], unique=False)
    op.create_index(op.f('ix_record_img_plate_exit_id'), 'record', ['img_plate_exit_id'], unique=False)
    op.drop_constraint('record_best_lpr_image_id_fkey', 'record', type_='foreignkey')
    op.drop_constraint('record_best_plate_image_id_fkey', 'record', type_='foreignkey')
    op.drop_constraint('record_price_model_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'image', ['img_plate_entrance_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'record', 'image', ['img_plate_exit_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'record', 'image', ['img_entrance_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'record', 'image', ['img_exit_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('record', 'best_lpr_image_id')
    op.drop_column('record', 'best_plate_image_id')
    op.drop_column('record', 'price_model_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('price_model_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('best_plate_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('record', sa.Column('best_lpr_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_price_model_id_fkey', 'record', 'price', ['price_model_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('record_best_plate_image_id_fkey', 'record', 'image', ['best_plate_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key('record_best_lpr_image_id_fkey', 'record', 'image', ['best_lpr_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_record_img_plate_exit_id'), table_name='record')
    op.drop_index(op.f('ix_record_img_plate_entrance_id'), table_name='record')
    op.drop_index(op.f('ix_record_img_exit_id'), table_name='record')
    op.drop_index(op.f('ix_record_img_entrance_id'), table_name='record')
    op.create_index('ix_record_price_model_id', 'record', ['price_model_id'], unique=False)
    op.create_index('ix_record_best_plate_image_id', 'record', ['best_plate_image_id'], unique=False)
    op.create_index('ix_record_best_lpr_image_id', 'record', ['best_lpr_image_id'], unique=False)
    op.drop_column('record', 'img_plate_exit_id')
    op.drop_column('record', 'img_plate_entrance_id')
    op.drop_column('record', 'img_exit_id')
    op.drop_column('record', 'img_entrance_id')
    # ### end Alembic commands ###
