"""equipment_status

Revision ID: cac97816ab88
Revises: 058a6339167c
Create Date: 2024-06-11 10:10:17.424941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac97816ab88'
down_revision = '058a6339167c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('equipment_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'equipment_status')
    # ### end Alembic commands ###
