"""change name type_camera to type_event

Revision ID: ce576526cf91
Revises: ea9c270d18f5
Create Date: 2024-10-02 09:35:54.097888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce576526cf91'
down_revision = 'ea9c270d18f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type_event', sa.String(), nullable=True))
    op.drop_column('event', 'type_camera')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('type_camera', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('event', 'type_event')
    # ### end Alembic commands ###
