"""create table price

Revision ID: d0eb1590a8a2
Revises: f362077751a2
Create Date: 2024-05-06 16:57:44.647820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0eb1590a8a2'
down_revision = 'f362077751a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price_model', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_created'), 'price', ['created'], unique=False)
    op.create_index(op.f('ix_price_id'), 'price', ['id'], unique=False)
    op.create_index(op.f('ix_price_is_deleted'), 'price', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_price_modified'), 'price', ['modified'], unique=False)
    op.drop_column('parking', 'price_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('price_model', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_price_modified'), table_name='price')
    op.drop_index(op.f('ix_price_is_deleted'), table_name='price')
    op.drop_index(op.f('ix_price_id'), table_name='price')
    op.drop_index(op.f('ix_price_created'), table_name='price')
    op.drop_table('price')
    # ### end Alembic commands ###
