"""refactor model record

Revision ID: d821d1d0257b
Revises: 8fb7d8a58b0b
Create Date: 2024-06-29 12:43:04.731148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd821d1d0257b'
down_revision = '8fb7d8a58b0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('best_lpr_image_id', sa.Integer(), nullable=True))
    op.drop_index('ix_record_best_lpr_id', table_name='record')
    op.create_index(op.f('ix_record_best_lpr_image_id'), 'record', ['best_lpr_image_id'], unique=False)
    op.drop_constraint('record_best_lpr_id_fkey', 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'image', ['best_lpr_image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_column('record', 'best_lpr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('best_lpr_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key('record_best_lpr_id_fkey', 'record', 'image', ['best_lpr_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_index(op.f('ix_record_best_lpr_image_id'), table_name='record')
    op.create_index('ix_record_best_lpr_id', 'record', ['best_lpr_id'], unique=False)
    op.drop_column('record', 'best_lpr_image_id')
    # ### end Alembic commands ###
