"""parkinglot_zone_id

Revision ID: e5712ae60be7
Revises: 890f63cf262f
Create Date: 2024-06-02 16:24:51.933529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5712ae60be7'
down_revision = '890f63cf262f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parkinglot', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parkinglot', 'parkingzone', ['zone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parkinglot', type_='foreignkey')
    op.drop_column('parkinglot', 'zone_id')
    # ### end Alembic commands ###
