"""create column price model id in table parking

Revision ID: e90e61a40771
Revises: 939fc994283a
Create Date: 2024-05-07 16:18:18.480869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90e61a40771'
down_revision = '939fc994283a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('price_model_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parking_price_model_id'), 'parking', ['price_model_id'], unique=False)
    op.create_foreign_key(None, 'parking', 'price', ['price_model_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parking', type_='foreignkey')
    op.drop_index(op.f('ix_parking_price_model_id'), table_name='parking')
    op.drop_column('parking', 'price_model_id')
    # ### end Alembic commands ###
