"""add column tag to equipment

Revision ID: ea9c270d18f5
Revises: 704c1014a373
Create Date: 2024-09-23 14:15:55.246393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9c270d18f5'
down_revision = '704c1014a373'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment', sa.Column('tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment', 'tag')
    # ### end Alembic commands ###
