"""new pricing

Revision ID: eae0c509654e
Revises: 4c6ca9d3e32a
Create Date: 2024-08-31 17:31:47.529462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eae0c509654e'
down_revision = '4c6ca9d3e32a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('entrance_fee', sa.Float(), nullable=True))
    op.add_column('price', sa.Column('hourly_fee', sa.Float(), nullable=True))
    op.drop_column('price', 'price_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('price_model', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('price', 'hourly_fee')
    op.drop_column('price', 'entrance_fee')
    # ### end Alembic commands ###
