"""add column into bill

Revision ID: ee554e14f560
Revises: 725407b4fc3a
Create Date: 2024-11-27 12:50:46.261101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee554e14f560'
down_revision = '725407b4fc3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill', sa.Column('notice_sent_at', sa.DateTime(), nullable=True))
    op.add_column('bill', sa.Column('notice_sent_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_bill_notice_sent_at'), 'bill', ['notice_sent_at'], unique=False)
    op.create_index(op.f('ix_bill_notice_sent_by'), 'bill', ['notice_sent_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_notice_sent_by'), table_name='bill')
    op.drop_index(op.f('ix_bill_notice_sent_at'), table_name='bill')
    op.drop_column('bill', 'notice_sent_by')
    op.drop_column('bill', 'notice_sent_at')
    # ### end Alembic commands ###
