"""fix fkey camra.image_id ondelete

Revision ID: f104376002fa
Revises: 4c510f7764e1
Create Date: 2024-06-16 12:00:16.200303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f104376002fa'
down_revision = '4c510f7764e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_image_id_fkey', 'camera', type_='foreignkey')
    op.create_foreign_key(None, 'camera', 'image', ['image_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('camera_image_id_fkey', 'camera', type_='foreignkey')
    op.create_foreign_key('camera_image_id_fkey', 'camera', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###
