"""sqlaclchemy2 model record

Revision ID: f1b47924e868
Revises: 52aba9d59cd9
Create Date: 2024-04-30 12:26:55.757508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b47924e868'
down_revision = '52aba9d59cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocr', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('best_lpr_id', sa.Integer(), nullable=False),
    sa.Column('best_big_image_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_big_image_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['best_lpr_id'], ['image.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_best_big_image_id'), 'record', ['best_big_image_id'], unique=False)
    op.create_index(op.f('ix_record_best_lpr_id'), 'record', ['best_lpr_id'], unique=False)
    op.create_index(op.f('ix_record_created'), 'record', ['created'], unique=False)
    op.create_index(op.f('ix_record_end_time'), 'record', ['end_time'], unique=False)
    op.create_index(op.f('ix_record_id'), 'record', ['id'], unique=False)
    op.create_index(op.f('ix_record_is_deleted'), 'record', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_record_modified'), 'record', ['modified'], unique=False)
    op.create_index(op.f('ix_record_ocr'), 'record', ['ocr'], unique=False)
    op.create_index(op.f('ix_record_score'), 'record', ['score'], unique=False)
    op.create_index(op.f('ix_record_start_time'), 'record', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_start_time'), table_name='record')
    op.drop_index(op.f('ix_record_score'), table_name='record')
    op.drop_index(op.f('ix_record_ocr'), table_name='record')
    op.drop_index(op.f('ix_record_modified'), table_name='record')
    op.drop_index(op.f('ix_record_is_deleted'), table_name='record')
    op.drop_index(op.f('ix_record_id'), table_name='record')
    op.drop_index(op.f('ix_record_end_time'), table_name='record')
    op.drop_index(op.f('ix_record_created'), table_name='record')
    op.drop_index(op.f('ix_record_best_lpr_id'), table_name='record')
    op.drop_index(op.f('ix_record_best_big_image_id'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
