"""add column into table and event

Revision ID: f2bc3fcf6b81
Revises: c0d9bd429260
Create Date: 2024-10-30 13:09:04.252676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2bc3fcf6b81'
down_revision = 'c0d9bd429260'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('additional_data', sa.JSON(), nullable=True))
    op.add_column('event', sa.Column('direction_info', sa.JSON(), nullable=True))
    op.add_column('event', sa.Column('correct_ocr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'correct_ocr')
    op.drop_column('event', 'direction_info')
    op.drop_column('event', 'additional_data')
    # ### end Alembic commands ###
