"""fix releation

Revision ID: fc0cf1a4c2e6
Revises: ac4924b0a38d
Create Date: 2024-06-24 13:31:29.864692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0cf1a4c2e6'
down_revision = 'ac4924b0a38d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
