[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Kamran Abdi <kamranabdicse@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
gunicorn = "^20.1.0"
pydantic = {version = "^2.5.1", extras = ["email"]}
psycopg2-binary = "^2.9.5"
alembic = "^1.9.1"
SQLAlchemy = "^2.0.23"
celery = "^5.2.7"
fastapi = {version = "^0.104.0", extras = ["all"]}
python-jose = "^3.3.0"
passlib = "^1.7.4"
persiantools = "^3.0.1"
python-multipart = "^0.0.5"
tenacity = "^8.1.0"
rocketry = "^2.5.1"
fakeredis = "^2.10.0"
aioredis = "^2.0.1"
redis = "^4.5.1"
asyncpg = "^0.27.0"
pytz = "^2023.3.post1"
pandas = "^2.2.0"
xlsxwriter = "^3.1.9"
openpyxl = "^3.1.2"
asgi-logger = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest="*"
black="*"
ruff="*"
isort="*"

[tool.black]
line-length = 79
exclude = '''
(
  .*versions/*
)
'''

[tool.ruff]
select = [
    "E",
    "W",
    "F",
    # "I",  # isort
    "C",
    "B",
]
ignore = [
    "E501",
    "B008",
]
exclude = ["versions"]
unfixable = ["E712", "B010"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"app/db/base.py" = ["F401"]

[tool.ruff.isort]
known-third-party = ["pydantic"]

[tool.isort]
profile = "black"
skip = ["versions"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
